name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install required packages
      run: sudo apt-get install libpq-dev libsqlite3-dev
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Install bundler
      run: gem install bundler -v 1.7.2
    - name: Cache gems
      uses: actions/cache@v1
      env:
        cache-name: cache-gems
      with:
        path: vendor/cache
        key: ruby-gems-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          ruby-gems-${{ hashFiles('Gemfile.lock') }}
          ruby-gems-
          ruby-
    - name: Install gems
      run: bundle check || bundle install -j $(nproc)
    - name: Run tests
      run: bundle exec rake
