name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install required packages
      run: sudo apt-get install libpq-dev libsqlite3-dev
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Install bundler
      run: gem install bundler -v 1.7.2
    - name: Install gems
      run: bundle install --jobs 4 --retry 3
    - name: Run tests
      run: bundle exec rake
